### ISSUE TITLE
Add Template Distribution gadget to side

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#123]
**Is your feature request related to a problem? Please describe.**
Now that we have template as a filter option, and we have some space on the right side next to the org metric. It would be great to also show a distribution component for templates.

There should already be an aragonUI component:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/4986634/72196582-3f426800-33e7-11ea-9466-a6ff1ebaba24.png">

**Comment by onbjerg** [comment]
We're moving away from templates as a center-piece in Apiary after #200 (I think?)
