### ISSUE TITLE
Support Fundraising template

### ISSUE THREAD

**Issue by izqui** [1Hive/apiary#128]
- Repo: [`fundraising-multisig-template.aragonpm.eth`](https://github.com/aragon/deployments/blob/master/environments/mainnet/deploys.yml#L826)
- Current template: https://etherscan.io/address/0xd4bc1afd46e744f1834cad01b2262d095dcb6c9b

**Comment by onbjerg** [comment]
Thanks!

**Comment by onbjerg** [comment]
This has been released but we will re-index Fundraising orgs at a later time.
