### ISSUE TITLE
Sort and filter by DAO activity

### ISSUE THREAD

**Issue by sembrestels** [1Hive/apiary#133]
**Is your feature request related to a problem? Please describe.**
Organizations can only be sorted alphabetically and by creation date, and they can only be filtered by apps, templates, and creation time. It is not enough to understand what is going on with DAOs, and activity volume (#41) is a valuable metric to add to the frontend.

**Describe the solution you'd like**
Include sorting and filtering by activity, and in the side panel show an activity aggregate of all DAOs by periods of time (last day, last week, last month), and a graph showing the activity distribution among DAOs.

![screenshot](https://i.imgur.com/cql4t93.png)

**Describe alternatives you've considered**
N/A

**Additional context**
We have committed to do this in this [CFDAO proposal](https://forum.aragon.org/t/daolist-is-now-apiary-an-aragon-dao-explorer/1199).

**Comment by lkngtn** [comment]
is there already an aragonUI component for the line chart? If not I think we should hold off on that for now.

**Comment by onbjerg** [comment]
@lkngtn No, I don't think they got around to adding that to aUI yet.

**Comment by onbjerg** [comment]
@lkngtn Yes, https://ui.aragon.org/line-chart/, but last time I used it it was not super ergonomic and I had a lot of trouble getting it to position properly without overflowing etc.

**Comment by onbjerg** [comment]
Activity is no longer a metric (at least for now) after #200
