### ISSUE TITLE
Sorting by columns also filters results

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#139]
**Describe the bug**
If I sort by activity (decending) and paginate to the end, there are no orgs with 0 activity. However if I sort by activity (ascending) I see organizations with 0/null activity. 

**To Reproduce**
See above

**Expected behavior**
Changing sort order should **never** impact which elements are shown in the table. 

**Additional context**
Using a local build of master.

**Comment by onbjerg** [comment]
No longer present/reproducible
