### ISSUE TITLE
App Mining Payout Projection

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#143]
**Is your feature request related to a problem? Please describe.**
Because payouts will depend on a whitelisted set of applications, the raw score does not necessarily give you a sense of payout amount. 

Payouts can be calculated using the following formula:

appscore / total_eligible_appscores * pot_amount. 

Currently assuming the pot amount is 100K ANT. I will create a seperate address book to manage the whitelist. 

**Describe the solution you'd like**
We should show two new columns on the apps page:

**Eligibility**: (indicating 🟢,🟡,🔴) for whitelisted, unregistered, and blacklisted respectively
**Projected Payout**: the ANT amount based on current scores and whitelist status.

**Describe alternatives you've considered**

**Additional context**

**Comment by onbjerg** [comment]
No longer in scope?
