### ISSUE TITLE
Add filters for activity, aum, ant, and score

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#144]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to filter by things like `AUM > 100` or `Activity > 10` and see how many organizations meet that criteria. Initial it may be okay if this is just possible via graphql endpoint but would those filters seem more useful than the app filter so probably also worth including in the front end.

**Comment by onbjerg** [comment]
Activity and such metrics do not exist after #200
