### ISSUE TITLE
Layout does not scale to fit 13" MacBook Pro

### ISSUE THREAD

**Issue by onbjerg** [1Hive/apiary#170]
**Describe the bug**

![image](https://user-images.githubusercontent.com/8862627/74821532-0f4e8480-5304-11ea-995b-b4b2c726cb4c.png)

**To Reproduce**
1. Get a 13" MacBook Pro
2. Open Apiary in maximized view
3. Sort by created descending
4. See the horror

**Expected behavior**
The layout table columns should be clearly separate and the content should not overlap the sidebar.

**Additional context**

I suspect the bug is mostly caused by the organisation name `939F24465226C77E8B9416AEE3B4ED4BCD68B45A02AE4C0DFAFAF6A65B740511.aragonid.eth`, since it is not present on the front page. A possible fix is to shorten the names in the `DataView`.

**Comment by onbjerg** [comment]
@lkngtn Looks like this is an org you participate in. Is this an OpenLaw org? If so, we should think about shortening the name of OL orgs in general.

**Comment by lkngtn** [comment]
This issue is impacting me whenever I creep on dandelion orgs. I think we should determine a reasonable length and if the name is over just show the address. Perhaps anything over 42 characters we shorten in this way?
