### ISSUE TITLE
Update style to match new aragonUI version

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#6]
We can also move to a list view rather than cards to better allow for #5 

The extra space on the right can be used to display aggregate/summary stats about the DAOs. 

Mockup:

![image](https://user-images.githubusercontent.com/4986634/62338189-a0175d00-b4a5-11e9-8567-a1150bd1a0da.png)

**Comment by onbjerg** [comment]
Blocked by missing chart components
