### ISSUE TITLE
Add template filter

### ISSUE THREAD

**Issue by onbjerg** [1Hive/apiary#60]
It might be beneficial to have a template filter for now, until the app store is functional, since we're probably not going to see much divergence from these templates until then.

**Tasks**

- [ ] Expose template in API
- [ ] Add template filter in UI

**Comment by nicklasmoeller** [comment]
I talked briefly with @onbjerg about this yesterday.

@lkngtn how do you think these template options should be presented?

We've got [these templates](https://github.com/1Hive/apiary/blob/bb7cc410b5f0fc9766d6fbcd2db8ebf251b93f2e/worker/src/org/kits.js#L1-L28) to choose from, but some of them are just newer versions.

Would you like each version to be represented on the list, or should we merge those?

**Comment by lkngtn** [comment]
I think it would probably make sense to combine Democracy and Company (and related versions), as well as multisig and membership, since those newer templates effectively replaced the older version. For those I would use the new names so Membership, or Company.

I also think it might make sense now that we have the app view, to remove the app filter, and instead add "installs" to the app context menu?

**Comment by onbjerg** [comment]
>I also think it might make sense now that we have the app view, to remove the app filter, and instead add "installs" to the app context menu?

I'm not sure I follow

**Comment by lkngtn** [comment]
<img width="123" alt="image" src="https://user-images.githubusercontent.com/4986634/68883580-544c9480-06df-11ea-9c05-ee3127afa3e4.png">

Add a link to this called "installs" that would bring up the org view filtered to only show orgs with that app installed. (this way we don't need to worry about having a massive drop down of apps, or curate it specifically)

**Comment by onbjerg** [comment]
That should be a separate task, although it should be fairly easy to implement.

**Comment by lkngtn** [comment]
Makes sense: https://github.com/1Hive/apiary/issues/82
