### ISSUE TITLE
App Mining

### ISSUE THREAD

**Issue by lkngtn** [1Hive/apiary#74]
Budget 50K DAI

 ## Mandate

To develop and launch an App Mining program where we reward publishers of Aragon Apps based on an agreed upon set of usage KPIs. The KPIs will be used to compute an Organization Score and from that an Application Score. 

 **The following KPIs are what we will initially focus on implementing**

|KPI|Definition|Proposed Weight|
| --- | --- | --- |
|ANT|Sum of ANT in held in each app in an organization.|25%|
|AUM (Assets Under Management)|Sum of the value in DAI of ETH, ANT, DAI, USDC held in each app in an organization.|25%|
|Activity|Sum of transactions involving any of the organizations apps in the last 90 day period|50%|

To compute the organization score each KPI would be normalized using as a ratio across all organizations, then KPIs will be combined into a single score using a weighted average. 

For example if an Org holds 100 ANT and the total amount of ANT held across all organizations is 1000 ANT, then the normalized ANT KPI would be 10%. The same process would be used to normalized AUM and Activity. To compute the organization score we would take ANT * .25 + AUM * .25 + Activity * .50. Let’s say the values for our example org are 10%, 20%, 30% respectively. The organization score would be 22.5%.

Then to compute the application score we would take the organization score and divide it by the number of applications installed in the organization, allocating the fractional amount to each installed application. We would compute a score for all applications regardless of whether the publisher has opted in to the App Mining program, but would exclude them publishers who have not opted in from payout calculation. If the example organization score is 22.5% and has 8 apps installed, the organization would contribute 2.81% to each app’s score.

**Comment by onbjerg** [comment]
Related issues:

- #13 Track app updates for orgs
- #16 Track activity
- #41 Track activity volume
- #42 Track number of unique address interactions
- #43 Track organization assets
